version: '3.8'

services:
  # Frontend application
  art-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: art-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - art-network

  # Development service (optional - for development with hot reload)
  art-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: art-frontend-dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - art-network

networks:
  art-network:
    driver: bridge 